'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AllSurveys

    '''<summary>
    '''OverlayPageSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OverlayPageSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''EnterYourPinLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnterYourPinLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''CancelOverlay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelOverlay As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SurveyNameComboBoxPin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameComboBoxPin As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''PinTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PinTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''PinMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PinMessage As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''EnterPinButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnterPinButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SurveyNameComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameComboBox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RefreshSurveyButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefreshSurveyButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ShowOverlayButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowOverlayButton As Global.Telerik.Web.UI.RadImageButton

    '''<summary>
    '''SurveysListView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveysListView As Global.Telerik.Web.UI.RadListView
End Class
