'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewAllSurveysPage

    '''<summary>
    '''OverlayPageSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OverlayPageSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CancelOverlayButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelOverlayButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ConfirmSurveyDeleteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmSurveyDeleteButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SurveyIdHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyIdHidden As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''GoBackButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoBackButton As Global.Telerik.Web.UI.RadImageButton

    '''<summary>
    '''SurveysListViewUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveysListViewUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SurveysListView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveysListView As Global.Telerik.Web.UI.RadListView
End Class
