'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SurveysHomePage

    '''<summary>
    '''OverlayPageSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OverlayPageSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NameYourSurveyLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameYourSurveyLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''CancelOverlay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelOverlay As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SurveyNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SurveyNameTakenLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameTakenLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''SurveyNameTextBoxValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameTextBoxValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CreateSurveyButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateSurveyButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CreateSurveyLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateSurveyLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''CreateSurveyImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateSurveyImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''CreateSurveyDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateSurveyDescriptionLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''ViewAllSurveylabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewAllSurveylabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''ViewAllSurveyImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewAllSurveyImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ViewAllSurveyDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewAllSurveyDescriptionLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''EditSurveysLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditSurveysLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''EditSurveysImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditSurveysImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''EditSurveysDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditSurveysDescriptionLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''DownloadSurveyslabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadSurveyslabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''DownloadSurveysImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadSurveysImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''DownloadSurveysDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadSurveysDescriptionLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''ViewDataAnalysisLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewDataAnalysisLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''ViewDataAnalysisImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewDataAnalysisImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ViewDataAnalysisDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewDataAnalysisDescription As Global.Telerik.Web.UI.RadLabel
End Class
