'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SurveyDesigningPage

    '''<summary>
    '''GoBackButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoBackButton As Global.Telerik.Web.UI.RadImageButton

    '''<summary>
    '''SurveyNameUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SurveyNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''SurveyNameTextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameTextbox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SurveyNameEditButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameEditButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SurveyNameSaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameSaveButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SurveyNameCancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurveyNameCancelButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''QuestionsUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionsUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''QuestionsListView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionsListView As Global.Telerik.Web.UI.RadListView

    '''<summary>
    '''NewQuestionUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewQuestionUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''NewQuestionButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewQuestionButton As Global.Telerik.Web.UI.RadImageButton

    '''<summary>
    '''NewQuestionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewQuestionPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CancelQuestionButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelQuestionButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''NewQuestionNumeberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewQuestionNumeberLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''NewQuestionTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewQuestionTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ControlsCombobox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsCombobox As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''NewQuestionTextBoxValidatorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewQuestionTextBoxValidatorLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''NewQuestionDescriptionTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewQuestionDescriptionTextBox As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''MandatoryQuestionCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MandatoryQuestionCheck As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''ControlPanels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlPanels As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadioButtonPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MinimumResponsesLabelRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinimumResponsesLabelRB As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''SaveRadioQuestionsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveRadioQuestionsButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''MultipleCheckBoxPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultipleCheckBoxPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MinimumResponsesLabelMB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinimumResponsesLabelMB As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''SaveMultipleQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveMultipleQuestions As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SliderPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SliderPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SliderOptionDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SliderOptionDropdown As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''SliderItemsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SliderItemsPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MinimumSliderResponsesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinimumSliderResponsesLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''MaximumSliderResponsesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaximumSliderResponsesLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''SliderSaveQuestionsItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SliderSaveQuestionsItems As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SliderRangePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SliderRangePanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ScaleRangeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScaleRangeLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''StartingRangeBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartingRangeBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''EndingRangeBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndingRangeBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''StepSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StepSizeLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''StepSizeBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StepSizeBox As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''NumericalCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumericalCheckBox As Global.Telerik.Web.UI.RadCheckBox

    '''<summary>
    '''IncorrectSliderRangeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncorrectSliderRangeLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''IncorrectStepRangeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncorrectStepRangeLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''SliderSaveQuestionsRanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SliderSaveQuestionsRanges As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SingleTextBoxPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SingleTextBoxPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SaveSingleTextBoxButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveSingleTextBoxButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CommentBoxPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommentBoxPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SaveCommmentBoxButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveCommmentBoxButton As Global.Telerik.Web.UI.RadButton
End Class
