'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserAccountPage

    '''<summary>
    '''AddUsersLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddUsersLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''AddUsersImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddUsersImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AddUsersDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddUsersDescriptionLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''DeleteUsersLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteUsersLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>
    '''DeleteUserImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteUserImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''DeleteUserDecriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteUserDecriptionLabel As Global.Telerik.Web.UI.RadLabel
End Class
